import random
import string
import os
import requests


card_list = [
    ["4000120000001154", "101"],
    ["4000130000001724", "102"],
    ["4000160000004147", "103"],
    ["4009830000001985", "200"],
    ["4242420000000091", "111"],
    ["5114610000004778", "101"],
    ["5114630000009791", "102"],
    ["5121220000006921", "103"],
    ["5135020000005871", "200"],
    ["5100000000000131", "111"],
    ["376525000000010", "101"],
    ["375425000000907", "102"],
    ["343452000000306", "103"],
    ["372349000000852", "200"],
    ["374205502001004", "111"],
    ["36256000000998", "101"],
    ["36256000000634", "102"],
    ["38865000000705", "103"],
    ["30450000000985", "200"],
    ["6011000000001010", "101"],
    ["6011000000001028", "102"],
    ["6011000000001036", "103"],
    ["6011000000002000", "200"],
    ["3566000000001016", "101"],
    ["3566000000001024", "102"],
    ["3566000000001032", "103"],
    ["3566000000002006", "200"],
    ["135400000009712", "101"],
    ["135400000007633", "102"],
    ["135400000000281", "103"],
    ["135400000005637", "205"]
]

names_list = [
        ['Jason', 'Brayden'], 
        ['Cole', 'Nathaniel'], 
        ['George', 'Lorenzo'], 
        ['Zion', 'Luis'], 
        ['Archer', 'Enzo'], 
        ['Jonah', 'Thiago'], 
        ['Theo', 'Ayden'], 
        ['Zachary', 'Calvin'], 
        ['Braxton', 'Ashton'], 
        ['Rhett', 'Atlas'], 
        ['Jude', 'Bentley'], 
        ['Carlos', 'Ryker'], 
        ['Adriel', 'Arthur'], 
        ['Ace', 'Tyler'], 
        ['Jayce', 'Max'], 
        ['Elliot', 'Graham'], 
        ['Kaiden', 'Maxwell'], 
        ['Juan', 'Dean'], 
        ['Matteo', 'Malachi'], 
        ['Ivan', 'Elliott'], 
        ['Jesus', 'Emiliano'], 
        ['Messiah', 'Gavin'], 
        ['Maddox', 'Camden'], 
        ['Hayden', 'Leon'], 
        ['Antonio', 'Justin'], 
        ['Tucker', 'Brandon'], 
        ['Kevin', 'Judah'], 
        ['Finn', 'King'], 
        ['Brody', 'Xander'], 
        ['Nicolas', 'Charlie'], 
        ['Arlo', 'Emmanuel'], 
        ['Barrett', 'Felix'], 
        ['Alex', 'Miguel'], 
        ['Abel', 'Alan'], 
        ['Beckett', 'Amari'], 
        ['Karter', 'Timothy'], 
        ['Abraham', 'Jesse'], 
        ['Zayden', 'Blake'], 
        ['Alejandro', 'Dawson'], 
        ['Tristan', 'Victor'], 
        ['Avery', 'Joel'], 
        ['Grant', 'Eric'], 
        ['Patrick', 'Peter'], 
        ['Richard', 'Edward'], 
        ['Andres', 'Emilio'], 
        ['Colt', 'Knox'], 
        ['Beckham', 'Adonis'], 
        ['Kyrie', 'Matias'], 
        ['Oscar', 'Lukas'], 
        ['Marcus', 'Hayes'], 
        ['Caden', 'Remington'], 
        ['Griffin', 'Nash'], 
        ['Israel', 'Steven'], 
        ['Holden', 'Rafael'], 
        ['Zane', 'Jeremy'], 
        ['Kash', 'Preston'], 
        ['Kyler', 'Jax'], 
        ['Jett', 'Kaleb'], 
        ['Riley', 'Simon'], 
        ['Phoenix', 'Javier'], 
        ['Bryce', 'Louis'], 
        ['Mark', 'Cash'], 
        ['Lennox', 'Paxton'], 
        ['Malakai', 'Paul'], 
        ['Kenneth', 'Nico'], 
        ['Kaden', 'Lane'], 
        ['Kairo', 'Maximus'], 
        ['Omar', 'Finley'], 
        ['Atticus', 'Crew'], 
        ['Brantley', 'Colin'], 
        ['Dallas', 'Walter'], 
        ['Brady', 'Callum'], 
        ['Ronan', 'Hendrix'], 
        ['Jorge', 'Tobias'], 
        ['Clayton', 'Emerson'], 
        ['Damien', 'Zayn'], 
        ['Malcolm', 'Kayson'], 
        ['Bodhi', 'Bryan'], 
        ['Aidan', 'Cohen'], 
        ['Brian', 'Cayden'], 
        ['Andre', 'Niko'], 
        ['Maximiliano', 'Zander'], 
        ['Khalil', 'Rory'], 
        ['Francisco', 'Cruz'], 
        ['Kobe', 'Reid'], 
        ['Daxton', 'Derek'], 
        ['Martin', 'Jensen'], 
        ['Karson', 'Tate'], 
        ['Muhammad', 'Jaden'], 
        ['Joaquin', 'Josue'], 
        ['Gideon', 'Dante'], 
        ['Cody', 'Bradley'], 
        ['Orion', 'Spencer'], 
        ['Angelo', 'Erick'], 
        ['Jaylen', 'Julius'], 
        ['Manuel', 'Ellis'], 
        ['Colson', 'Cairo'], 
        ['Gunner', 'Wade'], 
        ['Chance', 'Odin'], 
        ['Anderson', 'Kane'], 
        ['Raymond', 'Cristian'], 
        ['Aziel', 'Prince'], 
        ['Ezequiel', 'Jake'], 
        ['Otto', 'Eduardo'], 
        ['Rylan', 'Ali'], 
        ['Cade', 'Stephen'], 
        ['Ari', 'Kameron'], 
        ['Dakota', 'Warren'], 
        ['Ricardo', 'Killian'], 
        ['Mario', 'Romeo'], 
        ['Cyrus', 'Ismael'], 
        ['Russell', 'Tyson'], 
        ['Edwin', 'Desmond'], 
        ['Nasir', 'Remy'], 
        ['Tanner', 'Fernando'], 
        ['Hector', 'Titus'], 
        ['Lawson', 'Sean'], 
        ['Kyle', 'Elian'], 
        ['Corbin', 'Bowen'], 
        ['Wilder', 'Armani'], 
        ['Royal', 'Stetson'], 
        ['Briggs', 'Sullivan'], 
        ['Leonel', 'Callan'], 
        ['Finnegan', 'Jay'], 
        ['Zayne', 'Marshall'], 
        ['Kade', 'Travis'], 
        ['Sterling', 'Raiden'], 
        ['Sergio', 'Tatum'], 
        ['Cesar', 'Zyaire'], 
        ['Milan', 'Devin'], 
        ['Gianni', 'Kamari'], 
        ['Royce', 'Malik'], 
        ['Jared', 'Franklin'], 
        ['Clark', 'Noel'], 
        ['Marco', 'Archie'], 
        ['Apollo', 'Pablo'], 
        ['Garrett', 'Oakley'], 
        ['Memphis', 'Quinn'], 
        ['Onyx', 'Alijah'], 
        ['Baylor', 'Edgar'], 
        ['Nehemiah', 'Winston'], 
        ['Major', 'Rhys'], 
        ['Forrest', 'Jaiden'], 
        ['Reed', 'Santino'], 
        ['Troy', 'Caiden'], 
        ['Harvey', 'Collin'], 
        ['Solomon', 'Donovan'], 
        ['Damon', 'Jeffrey'], 
        ['Kason', 'Sage'], 
        ['Grady', 'Kendrick'], 
        ['Leland', 'Luciano'], 
        ['Pedro', 'Hank'], 
        ['Hugo', 'Esteban'], 
        ['Johnny', 'Kashton'], 
        ['Ronin', 'Ford']
    ]

expireations_list = [
        ['01', '2022'],
        ['02', '2022'],
        ['03', '2022'],
        ['04', '2022'],
        ['05', '2022'],
        ['06', '2022'],
        ['07', '2022'],
        ['08', '2022'],
        ['09', '2022'],
        ['10', '2022'],
        ['11', '2022'],
        ['12', '2022'],
        ['01', '2023'],
        ['02', '2023'],
        ['03', '2023'],
        ['04', '2023'],
        ['05', '2023'],
        ['06', '2023'],
        ['07', '2023'],
        ['08', '2023'],
        ['09', '2023'],
        ['10', '2023'],
        ['11', '2023'],
        ['12', '2023'],
        ['01', '2024'],
        ['02', '2024'],
        ['03', '2024'],
        ['04', '2024'],
        ['05', '2024'],
        ['06', '2024'],
        ['07', '2024'],
        ['08', '2024'],
        ['09', '2024'],
        ['10', '2024'],
        ['11', '2024'],
        ['12', '2024'],
        ['01', '2025'],
        ['02', '2025'],
        ['03', '2025'],
        ['04', '2025'],
        ['05', '2025'],
        ['06', '2025'],
        ['07', '2025'],
        ['08', '2025'],
        ['09', '2025'],
        ['10', '2025'],
        ['11', '2025'],
        ['12', '2025'],
        ['01', '2026'],
        ['02', '2026'],
        ['03', '2026'],
        ['04', '2026'],
        ['05', '2026'],
        ['06', '2026'],
        ['07', '2026'],
        ['08', '2026'],
        ['09', '2026'],
        ['10', '2026'],
        ['11', '2026'],
        ['12', '2026']
]

phone_codes =     [
        201,
        202,
        203,
        204,
        205,
        206,
        207,
        208,
        209,
        210,
        211,
        212,
        213,
        214,
        215,
        216,
        217,
        218,
        219,
        224,
        225,
        228,
        229,
        231,
        234,
        236,
        239,
        240,
        242,
        246,
        248,
        249,
        250,
        251,
        252,
        253,
        254,
        256,
        260,
        262,
        264,
        267,
        268,
        269,
        270,
        276,
        278,
        280,
        281,
        282,
        283,
        284,
        289,
        301,
        302,
        303,
        304,
        305,
        306,
        307,
        308,
        309,
        310,
        311,
        312,
        313,
        314,
        315,
        316,
        317,
        318,
        319,
        320,
        321,
        323,
        325,
        327,
        330,
        331,
        334,
        336,
        337,
        339,
        340,
        341,
        345,
        347,
        351,
        352,
        353,
        354,
        358,
        360,
        361,
        369,
        380,
        381,
        383,
        385,
        386,
        401,
        402,
        403,
        404,
        405,
        406,
        407,
        408,
        409,
        410,
        411,
        412,
        413,
        414,
        415,
        416,
        417,
        418,
        419,
        420,
        423,
        424,
        425,
        430,
        432,
        434,
        435,
        438,
        440,
        441,
        442,
        443,
        445,
        450,
        456,
        464,
        469,
        470,
        473,
        475,
        478,
        479,
        480,
        484,
        500,
        501,
        502,
        503,
        504,
        505,
        506,
        507,
        508,
        509,
        510,
        511,
        512,
        513,
        514,
        515,
        516,
        517,
        518,
        519,
        520,
        530,
        540,
        541,
        546,
        551,
        555,
        557,
        559,
        561,
        562,
        563,
        564,
        567,
        570,
        571,
        573,
        574,
        580,
        585,
        586,
        590,
        600,
        601,
        602,
        603,
        604,
        605,
        606,
        607,
        608,
        609,
        610,
        611,
        612,
        613,
        614,
        615,
        616,
        617,
        618,
        619,
        620,
        623
    ]

strt_ending = ["street", "Street", "dr", "drive", "Driver", "st", "Dr", "St"]

city_state_list = [
        ["New York City", "NY"],
        ["Los Angeles", "CA"],
        ["Chicago", "IL"],
        ["Houston", "TX"],
        ["Phoenix", "AZ"],
        ["Philadelphia", "PA"],
        ["San Antonio", "TX"],
        ["San Diego", "CA"],
        ["Dallas", "TX"],
        ["San Jose", "CA"]
    ]

person = ["jack", "Oniel"]

password_list = [
        "ruben",
        "platinum",
        "leticia",
        "german",
        "snowman",
        "romero",
        "madeline",
        "dulce",
        "turkey",
        "sweetgirl",
        "sayangku",
        "pancho",
        "mandy",
        "lollol",
        "edison",
        "ashanti",
        "angel12",
        "rocknroll",
        "andreia",
        "Princess",
        "freckles",
        "yousuck",
        "juanito",
        "ismael",
        "chingy",
        "taekwondo",
        "freedom1",
        "ericka",
        "020202",
        "franco",
        "celine",
        "trinidad",
        "smokey1",
        "promise",
        "jeremy1",
        "angel2",
        "alexandre",
        "ganteng",
        "arcangel",
        "julia",
        "precious1",
        "asd123",
        "jacob1",
        "cowgirl",
        "peaches1",
        "melinda",
        "sixteen",
        "qazwsxedc",
        "mustang1",
        "budlight",
        "newyork1",
        "loveyou2",
        "iluvu2",
        "cracker",
        "renato",
        "kenshin",
        "phantom",
        "loveable",
        "laptop",
        "hamilton",
        "fuckit",
        "blessed1",
        "virgo",
        "1bitch",
        "shauna",
        "private",
        "isabelle",
        "biatch",
        "surfer",
        "passport",
        "lynlyn",
        "kayla1",
        "bobmarley",
        "babykoh",
        "picture",
        "logan",
        "jesusfreak",
        "harris",
        "doodle",
        "sexybaby",
        "pink",
        "lizbeth",
        "bubba",
        "triskelion",
        "tootsie",
        "thalia",
        "rolando",
        "ilovemike",
        "apple1",
        "valencia",
        "shawn",
        "rommel",
        "maemae",
        "felicidad",
        "cheese1",
        "student",
        "rainbow1",
        "confused",
        "cellphone",
        "aldrin",
        "paris",
        "minime",
        "marion",
        "ewanko",
        "stormy",
        "sisters",
        "rocket",
        "queen",
        "lovers1",
        "slimshady",
        "steve",
        "poison",
        "florence",
        "rey619",
        "delete",
        "cristal",
        "yomama",
        "spooky",
        "pimpin1",
        "maricel",
        "gizmo1",
        "dondon",
        "divine",
        "chucky",
        "aries",
        "rowena",
        "nokia",
        "stitch",
        "jerry",
        "hazel",
        "maimai",
        "jackson1",
        "nataly",
        "emily1",
        "swimmer",
        "pussy",
        "loveyou1",
        "liverpool1",
        "lauren1",
        "chloe1",
        "jonathan1",
        "soloyo",
        "jonasbrothers",
        "eminem1",
        "anything",
        "nickjonas",
        "vodafone",
        "punkin",
        "mnbvcxz",
        "forget",
        "babes",
        "tasha",
        "magandaako",
        "madrid",
        "scruffy",
        "paige",
        "motocross",
        "colorado",
        "321654",
        "skyler",
        "sidney",
        "bryant",
        "malibu",
        "galaxy",
        "cruzazul",
        "paolita",
        "getmoney",
        "filipe",
        "applepie",
        "454545",
        "insane",
        "princes",
        "morado",
        "laurita",
        "country",
        "theused",
        "beatrice",
        "gunner",
        "greenday1",
        "edwin",
        "cinta",
        "ROCKYOU",
        "shanice",
        "kagome",
        "sherry",
        "penelope",
        "password3",
        "morgan1",
        "kakashi",
        "falcon",
        "alabama",
        "irock",
        "dorothy",
        "beverly",
        "avril",
        "hanson",
        "redhead",
        "germany",
        "regine",
        "marijuana",
        "121314",
        "rakista",
        "jenna",
        "escorpion",
        "weed420",
        "oscar1",
        "love15",
        "hihihi",
        "amazing",
        "nevaeh",
        "marimar",
        "jamie1",
        "DANIEL",
        "mypassword",
        "philips",
        "johana",
        "ilove",
        "hitman",
        "trandafir",
        "shannon1",
        "myfamily",
        "monalisa",
        "bonjovi",
        "xander",
        "scooby1",
        "robinson",
        "church",
        "wonderful",
        "potpot",
        "lucas",
        "password!",
        "zoey101",
        "qwerty123",
        "georgina",
        "bigred",
        "tonton",
        "telefon",
        "stuart",
        "pavilion",
        "chivas1",
        "jenifer",
        "jaime",
        "dance1",
        "aishiteru",
        "stardust",
        "grapes",
        "fatcat",
        "angel13",
        "milton",
        "bowwow1",
        "fofinha",
        "eddie",
        "tinker1",
        "doctor",
        "abercrombie",
        "pink12",
        "georgiana",
        "conner",
        "astig",
        "system",
        "candyfloss",
        "alondra",
        "winniethepooh",
        "love143",
        "g-unit",
        "iloveme2",
        "gizmo",
        "donnie",
        "brittany1",
        "bamboo",
        "katie1",
        "devils",
        "cathy",
        "bobby1",
        "benson",
        "a1b2c3",
        "tattoo",
        "skipper",
        "eleven",
        "cinnamon",
        "bernie",
        "psycho",
        "mypics",
        "mobile",
        "langga",
        "iloveryan",
        "falcons",
        "cowboys1",
        "alyssa1",
        "emilia",
        "050505",
        "spoiled",
        "antony",
        "allen",
        "respect",
        "princess2",
        "angeleyes",
        "american",
        "nemesis",
        "nathalie",
        "famous",
        "cedric",
        "wolverine",
        "snoopy1",
        "nelly",
        "madden",
        "13579",
        "shawty",
        "payton",
        "lifesucks",
        "broncos",
        "amalia",
        "alina",
        "monkey2",
        "mikaela",
        "emogirl",
        "963852741",
        "poncho",
        "gibson",
        "denisse",
        "303030",
        "292929",
        "sheryl",
        "super",
        "sonia",
        "pinky1",
        "chantelle",
        "puertorico",
        "meandyou",
        "marcel",
        "krissy",
        "kittie",
        "sprite",
        "manman",
        "kimmie",
        "hotboy",
        "emerson",
        "elamor",
        "capricornio",
        "black1",
        "misty",
        "lillian",
        "fuckoff1",
        "chelsey",
        "suzuki",
        "octubre",
        "magdalena",
        "bratz",
        "tomtom",
        "noodle",
        "carebears",
        "flamingo",
        "deborah",
        "tiffany1",
        "renee",
        "noviembre",
        "420420",
        "kenken",
        "gabriella",
        "dietcoke",
        "behappy",
        "1123581321",
        "marianne",
        "brianna1",
        "abcdefgh",
        "skyblue",
        "irene",
        "bombon",
        "anjing",
        "raven",
        "donna",
        "wedding",
        "sexy13",
        "chikita",
        "asawako",
        "wordpass",
        "naynay",
        "mariajose",
        "lionking",
        "devil",
        "xiomara",
        "soccer12",
        "music1",
        "moocow",
        "maritza",
        "samsam",
        "ivonne",
        "rodolfo",
        "lovable",
        "ilovepink",
        "hannahmontana",
        "girlfriend",
        "soccer10",
        "skateboard",
        "personal",
        "newport",
        "RockYou",
        "perrito",
        "nikki1",
        "mitch",
        "marine",
        "jesse1",
        "ilovemom",
        "pillow",
        "duckie",
        "brasil",
        "window",
        "rockers",
        "jamjam",
        "conejita",
        "mylove1",
        "lopez",
        "josue",
        "BABYGIRL",
        "sexyboy",
        "makaveli",
        "ilovejoe",
        "marcia",
        "007007",
        "southpark",
        "sherwin",
        "lestat",
        "desire",
        "445566",
        "pencil",
        "denden",
        "scooter1",
        "brazil",
        "boobies",
        "yankees1",
        "scarlet",
        "powers",
        "killua",
        "leandro",
        "burbuja",
        "bonjour",
        "armani",
        "poop",
        "nadia",
        "michigan",
        "astrid",
        "billybob",
        "theman",
        "sunday",
        "loquita",
        "kristy",
        "believe",
        "missyou",
        "english",
        "timmy",
        "simpson",
        "lennon",
        "frogger",
        "dingdong",
        "ssssss",
        "philly",
        "pepito",
        "naruto1",
        "lilman",
        "chelseafc",
        "blingbling",
        "batman1",
        "135790",
        "sparkles",
        "honeys",
        "graham",
        "flaquita",
        "dalejr"
    ]






